# Generated by Django 3.1.3 on 2022-02-08 11:53

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220208_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', max_length=150, null=True, upload_to=post.models.upload_location, width_field='width_field'),
        ),
    ]
